# Generated by Django 5.0.6 on 2026-08-19 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('medical', 'Medical'), ('fire', 'Fire'), ('accident', 'Accident'), ('crime', 'Crime/Safety Threat'), ('disaster', 'Natural Disaster')], max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('ai_summary', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_meters', models.IntegerField(default=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('responders_enroute', 'Responders En Route'), ('resolved', 'Resolved'), ('escalated', 'Escalated to Officials')], default='open', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('original_lang', models.CharField(default='en', max_length=10)),
                ('translated_text', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='incidents.incident')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OfficialHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_type', models.CharField(max_length=30)),
                ('report_payload', models.JSONField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('ack_status', models.CharField(default='sent', max_length=20)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handoff', to='incidents.incident')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('acknowledged', 'Acknowledged'), ('enroute', 'En Route'), ('arrived', 'Arrived')], default='acknowledged', max_length=20)),
                ('distance_meters', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='incidents.incident')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('incident', 'responder')},
            },
        ),
    ]
